const occupation_Arr = [
    "Accountant",
    "Actor/Actress",
    "Architect",
    "Author",
    "Chef",
    "Civil Engineer",
    "Data Scientist",
    "Dentist",
    "Doctor",
    "Electrician",
    "Event Planner",
    "Fashion Designer",
    "Financial Analyst",
    "Graphic Designer",
    "Human Resources Manager",
    "Interior Designer",
    "Journalist",
    "Lawyer",
    "Marketing Manager",
    "Mechanical Engineer",
    "Nurse",
    "Occupational Therapist",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Police Officer",
    "Software Developer",
    "Teacher",
    "Translator",
    "Travel Agent",
    "Veterinarian",
    "Web Developer",
    "Writer"
]

export default occupation_Arr;