const occupation_Arr = [
    "Student",
    "Software Developer",
    "Teacher",
    "Accountant",
    "Actor/Actress",
    "Architect",
    "Author",
    "Chef",
    "Civil Engineer",
    "Data Scientist",
    "Dentist",
    "Doctor",
    "Electrician",
    "Event Planner",
    "Fashion Designer",
    "Financial Analyst",
    "Graphic Designer",
    "Human Resources Manager",
    "Interior Designer",
    "Journalist",
    "Lawyer",
    "Marketing Manager",
    "Mechanical Engineer",
    "Nurse",
    "Occupational Therapist",
    "Pharmacist",
    "Photographer",
    "Physical Therapist",
    "Police Officer",
    "Translator",
    "Travel Agent",
    "Veterinarian",
    "Web Developer",
    "Writer",
    "Other"
]
const EDUCTION_OPTIONS = [
    "Less than High School",
    "High School Graduate",
    "Intermediate Graduate",
    "GED (General Educational Development)",
    "Vocational/Technical Certificate",
    "Some College, No Degree",
    "Associate Degree",
    "Bachelor's Degree",
    "Post-Baccalaureate Certificate",
    "Master's Degree",
    "Post-Master's Certificate",
    "Doctorate",
    "Professional Degree (e.g., MD, JD)",
    "Postdoctoral Studies",
    "Specialized Training/Certification",
    "Non-Degree Seeking",
    "Other",
];

export { EDUCTION_OPTIONS, occupation_Arr }