export const categoryArr = [
    { category: 'General', slug: '/SearchQuestion/General' },
    { category: 'Programming', slug: '/SearchQuestion/Programming' },
    { category: 'Business', slug: '/SearchQuestion/Business' },
    { category: 'Java', slug: '/SearchQuestion/Java' },
    { category: 'NoSQL', slug: '/SearchQuestion/NoSQL' },
    { category: 'Education', slug: '/SearchQuestion/Education' },
    { category: 'Database', slug: '/SearchQuestion/database' },
    { category: 'frameworks', slug: '/SearchQuestion/frameworks' },
    { category: 'Gaming', slug: '/SearchQuestion/Gaming' },
    { category: 'SQL', slug: '/SearchQuestion/sql' },
    { category: 'React', slug: '/SearchQuestion/react' },
    { category: 'Python', slug: '/SearchQuestion/python' },
    { category: 'Data Structures and Algorithms', slug: '/SearchQuestion/DataStructuresAlgorithms' },
    { category: 'Javascript', slug: '/SearchQuestion/javascript' },
    { category: 'Interview', slug: '/SearchQuestion/interview' },
    { category: 'Science & Technology', slug: '/SearchQuestion/ScienceTechnology' },
    { category: 'Machine Learning', slug: '/SearchQuestion/MachineLearning' },
    { category: 'Artificial Intelligence', slug: '/SearchQuestion/ArtificialIntelligence' },
]

