const categoriesArr = [
    { category: 'General', slug: '/SearchQuestion/General' },
    { category: 'Science & Technology', slug: '/SearchQuestion/ScienceTechnology' },
    { category: 'Programming', slug: '/SearchQuestion/Programming' },
    { category: 'Web Development', slug: '/SearchQuestion/WebDevelopment' },
    { category: 'Mobile Development', slug: '/SearchQuestion/MobileDevelopment' },
    { category: 'Business', slug: '/SearchQuestion/Business' },
    { category: 'Health', slug: '/SearchQuestion/Health' },
    { category: 'Travel', slug: '/SearchQuestion/Travel' },
    { category: 'Food', slug: '/SearchQuestion/Food' },
    { category: 'Education', slug: '/SearchQuestion/Education' },
    { category: 'Books', slug: '/SearchQuestion/Books' },
    { category: 'Movies', slug: '/SearchQuestion/Movies' },
    { category: 'Music', slug: '/SearchQuestion/Music' },
    { category: 'Gaming', slug: '/SearchQuestion/Gaming' },
    { category: 'Sports', slug: '/SearchQuestion/Sports' },
    { category: 'Fashion', slug: '/SearchQuestion/Fashion' },
    { category: 'Home & Living', slug: '/SearchQuestion/HomeLiving' },
    { category: 'Parenting', slug: '/SearchQuestion/Parenting' },
    { category: 'Relationships', slug: '/SearchQuestion/Relationships' },
    { category: 'Philosophy', slug: '/SearchQuestion/Philosophy' },
    { category: 'History', slug: '/SearchQuestion/History' },
    { category: 'Funny', slug: '/SearchQuestion/Funny' },
    { category: 'Environment', slug: '/SearchQuestion/Environment' },
    { category: 'Social Issues', slug: '/SearchQuestion/SocialIssues' },
]

export { categoriesArr }
